# Generated by Django 5.0 on 2025-05-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="DocumentChunk",
        ),
    ]
